# Generated by Django 5.2.10 on 2026-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="開始日時")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=0, verbose_name="練習時間（分）"),
                ),
                (
                    "chords_practiced",
                    models.JSONField(default=list, verbose_name="練習したコード"),
                ),
                (
                    "goal_achieved",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="目標達成フラグ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "練習セッション",
                "verbose_name_plural": "練習セッション",
                "db_table": "practice_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserChord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "practice_count",
                    models.IntegerField(default=0, verbose_name="練習回数"),
                ),
                (
                    "last_practiced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最終練習日時"
                    ),
                ),
                (
                    "proficiency_level",
                    models.SmallIntegerField(default=0, verbose_name="習熟度レベル"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "ユーザーコード",
                "verbose_name_plural": "ユーザーコード",
                "db_table": "user_chords",
                "ordering": ["user", "-proficiency_level", "chord"],
            },
        ),
    ]
