# Generated by Django 5.2.10 on 2026-01-27 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guitar", "0001_initial"),
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="practice_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AddField(
            model_name="userchord",
            name="chord",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_chords",
                to="guitar.chord",
                verbose_name="コード",
            ),
        ),
        migrations.AddField(
            model_name="userchord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_chords",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ユーザー",
            ),
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(fields=["user"], name="idx_practice_user"),
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(fields=["started_at"], name="idx_practice_started"),
        ),
        migrations.AlterUniqueTogether(
            name="userchord",
            unique_together={("user", "chord")},
        ),
    ]
