# Generated by Django 5.2.10 on 2026-01-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="コード名"
                    ),
                ),
                ("finger_positions", models.JSONField(verbose_name="指板位置")),
                (
                    "difficulty",
                    models.SmallIntegerField(default=1, verbose_name="難易度"),
                ),
                (
                    "diagram",
                    models.TextField(blank=True, verbose_name="コードダイアグラム"),
                ),
                (
                    "display_order",
                    models.SmallIntegerField(default=0, verbose_name="表示順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "コード",
                "verbose_name_plural": "コード",
                "db_table": "chords",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
