# Generated by Django 5.2.10 on 2026-01-27 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="実績名"),
                ),
                ("description", models.CharField(max_length=255, verbose_name="説明")),
                ("icon_url", models.TextField(blank=True, verbose_name="アイコンURL")),
                (
                    "tier",
                    models.SmallIntegerField(
                        choices=[(1, "ブロンズ"), (2, "シルバー"), (3, "ゴールド")],
                        default=1,
                        verbose_name="ティア",
                    ),
                ),
                (
                    "unlock_score",
                    models.IntegerField(default=0, verbose_name="解除スコア"),
                ),
                (
                    "display_order",
                    models.SmallIntegerField(default=0, verbose_name="表示順序"),
                ),
            ],
            options={
                "verbose_name": "実績",
                "verbose_name_plural": "実績",
                "db_table": "achievements",
                "ordering": ["display_order", "tier", "name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="曲名"),
                ),
                (
                    "artist",
                    models.CharField(max_length=255, verbose_name="アーティスト名"),
                ),
                (
                    "difficulty",
                    models.IntegerField(default=1, verbose_name="難易度（1-5）"),
                ),
                (
                    "tempo",
                    models.IntegerField(default=120, verbose_name="テンポ（BPM）"),
                ),
                (
                    "notes",
                    models.JSONField(default=list, verbose_name="ノートシーケンス"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, verbose_name="曲の長さ（秒）"),
                ),
                (
                    "display_order",
                    models.SmallIntegerField(default=0, verbose_name="表示順序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
            options={
                "verbose_name": "楽曲",
                "verbose_name_plural": "楽曲",
                "db_table": "songs",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="スコア")),
                (
                    "max_combo",
                    models.IntegerField(default=0, verbose_name="最大コンボ数"),
                ),
                (
                    "perfect_count",
                    models.IntegerField(default=0, verbose_name="パーフェクト数"),
                ),
                (
                    "great_count",
                    models.IntegerField(default=0, verbose_name="グレート数"),
                ),
                ("good_count", models.IntegerField(default=0, verbose_name="グッド数")),
                ("miss_count", models.IntegerField(default=0, verbose_name="ミス数")),
                ("accuracy", models.FloatField(default=0.0, verbose_name="精度（%）")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="プレイ日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.song",
                        verbose_name="楽曲",
                    ),
                ),
            ],
            options={
                "verbose_name": "ゲームセッション",
                "verbose_name_plural": "ゲームセッション",
                "db_table": "game_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SongNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_number", models.IntegerField(verbose_name="ノート番号（MIDI）")),
                ("timing", models.FloatField(verbose_name="タイミング（秒）")),
                ("note_name", models.CharField(max_length=10, verbose_name="ノート名")),
                (
                    "duration",
                    models.FloatField(default=0.5, verbose_name="持続時間（秒）"),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_notes",
                        to="game.song",
                        verbose_name="楽曲",
                    ),
                ),
            ],
            options={
                "verbose_name": "楽曲ノート",
                "verbose_name_plural": "楽曲ノート",
                "db_table": "song_notes",
                "ordering": ["song", "timing"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="スコア")),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.song",
                        verbose_name="楽曲",
                    ),
                ),
            ],
            options={
                "verbose_name": "スコア",
                "verbose_name_plural": "スコア",
                "db_table": "scores",
                "ordering": ["-date", "-score"],
                "unique_together": {("user", "song", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unlocked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="解除日時"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.achievement",
                        verbose_name="実績",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザー実績",
                "verbose_name_plural": "ユーザー実績",
                "db_table": "user_achievements",
                "ordering": ["-unlocked_at"],
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
